require conf/distro/poky.conf

DISTRO = "scalys"
DISTRO_NAME = "Scalys base distro"
DISTRO_VERSION = "1.0"

# Log information on images and packages
INHERIT += "buildhistory"
BUILDHISTORY_COMMIT ?= "1"

INIT_MANAGER = "systemd"

DISTRO_FEATURES:append = "seccomp virtualization security tpm2 ipv6 wifi bluetooth usbhost pci"

PACKAGE_CLASSES = "package_rpm"

